package fr.nothing.brewdogame;

import java.util.ArrayList;

public class Question {
    ArrayList <String> Questions = new ArrayList<>();

    public Question() {
        Questions.add("Qui est le plus intelligent ?");
        Questions.add("Qui a les meilleurs goûts musiquaux ?");
        Questions.add("Qui aurait la biographie la plus intérressante ?");
        Questions.add("Qui serait le plus a même d'éviter une bagarre ?");
        Questions.add("Qui tient mieux l'alcool ?");
        Questions.add("Qui est le plus bagarreur ?");
        Questions.add("Qui fume le plus de Weed ?");
        Questions.add("Qui joue le plus au jeux vidéo ?");
        Questions.add("Qui est le plus beau ?");
        Questions.add("Qui a le plus de véhicules ?");
        Questions.add("Qui fait le plus de kilomètres par an ?\nAuto/train/marche tout compte");
        Questions.add("Qui est le plus cultivé ?");
        Questions.add("Qui boit le plus ?");
        Questions.add("Qui a les meilleurs goûts cinématographiques ?");
        Questions.add("Qui est la meilleure fée du logis ?");
        Questions.add("Qui parle le plus ?");
        Questions.add("Qui serait le meilleur président ?");
        Questions.add("Qui ferait le meilleur super-héros ?");
        Questions.add("Qui ferait le plus maléfique des super-vilains");
        Questions.add("Qui passe le plus de temps sur les réseaux sociaux ?");
        Questions.add("Qui est le plus radin ?");
        Questions.add("Qui est le plus mature ?");
        Questions.add("Qui est le plus frileux ?");
        Questions.add("Qui est le plus honnête ?");
        Questions.add("Qui chante le mieux ?");
        Questions.add("Qui a le plus d'éthique ?");
        Questions.add("Qui a deux mains gauches ?");
        Questions.add("Qui est le plus mauvais chauffeur ?");
        Questions.add("Qui est le plus croyant ?");
        Questions.add("Qui est le plus naïf ?");
        Questions.add("Qui est le plus gamin ?");
        Questions.add("Qui est le plus fashion ?");
        Questions.add("Qui a le plus de répartie ?");
        Questions.add("Qui a le plus gros appétit ? (on ne parle pas de sexe !)");
        Questions.add("Qui garde le plus de choses inutiles ?");
        Questions.add("Qui a la meilleure mémoire ?");
        Questions.add("Qui le plus la tête deans le cul le matin ?");
        Questions.add("Qui est le plus un rayon de soleil ?");
        Questions.add("Qui est le plus drôle ?");
        Questions.add("Qui dit le plus des dictons de merde ?");
        Questions.add("Qui est le meilleur Shazam humain ?");

        //Passage Question Medium
        Questions.add("Qui se masturbe le plus ?");
        Questions.add("Qui a le plus d'Ex-conjoints ?");
        Questions.add("Qui a le plus beau conjoint ?");
        Questions.add("Qui serait le plus à même d'avoir un conjoint objet ?");
        Questions.add("Qui a eu le pire hangover ?");
        Questions.add("Qui a eu le prof le plus con ?");
        Questions.add("Qui est le plus con ?");
        Questions.add("Qui s'intérresse le plus à son apparence ?");
        Questions.add("Qui est le plus faignant ?");
        Questions.add("Qui est le plus fainéant ?");
        Questions.add("Qui est le plus gros alcoolique ?");
        Questions.add("Qui est le plus gros égocentrique ?");
        Questions.add("Qui a toujours raison ?");
        Questions.add("Qui a le plus beau cul ?");
        Questions.add("Qui est le plus Nagasaki aux chiottes ?");
        Questions.add("Qui est le plus chiant ?");
        Questions.add("Qui est le plus susceptible de se faire oublier à un fête ?");
        Questions.add("Qui embrasse le mieux ?");
        Questions.add("Qui est le meilleur menteur ?");
        Questions.add("Qui a le plus de tics ?");
        Questions.add("Qui est le concierge de service ?");
        Questions.add("Qui a la plus grande espérance de vie ?");
        Questions.add("Qui est le plus gros beauf ?");
        Questions.add("Qui devrait fermer sa gueule ?");
        Questions.add("Qui cache le plus gros secret ?");
        Questions.add("Qui contribue le moins à l'ambiance de cette soirée ?");
        Questions.add("Qui serait le meilleur à manger ?");
        Questions.add("Qui mangerait l'autre sur une île déserte ?");
        Questions.add("Qui se plaînt le plus ?");
        Questions.add("Qui est le plus salé ?");
        Questions.add("Qui a le plus gros rire de merde ?");
        Questions.add("Qui est le plus susceptible de transgresser les règles ?");
        Questions.add("Qui a le plus de complexes ?");
        Questions.add("Qui est le meilleur tricheur ?");
        Questions.add("Qui est le plus romantique ?");
        Questions.add("Qui est le meilleur grand frère ?");
        Questions.add("Qui a le pire caractère ?");
        Questions.add("Qui est le plus influençable ?");
        Questions.add("Qui s'estime le plus riche ?");
        Questions.add("Qui est un même à lui tout seul ?");
        Questions.add("Qui vendrait son âme au diable ?");
        //Passage Question hard
        Questions.add("Qui s'est masturbé dans l'endroit le plus étrange ?");
        Questions.add("Qui a les parents les plus étranges ?");
        Questions.add("Qui a le plus baisé ?");
        Questions.add("Qui serait le plus à même de tromper son conjoint ?");
        Questions.add("Qui a baisé le plus ?");
        Questions.add("Qui a tester le plus de drogues ?");
        Questions.add("Qui a commis le plus de crime ?");
        Questions.add("Qui a le plus de seins ?");
        Questions.add("Qui est le plus crade ?");
        Questions.add("Qui a l'esprit le plus pervers ?");
        Questions.add("Qui est le meilleur coup au lit ?");
        Questions.add("Qui coûterait le plus cher si il se prostituait ?");
        Questions.add("Qui a plus de moquette que de rideaux ?");
        Questions.add("Qui a le plus gros GENITAL ?");
        Questions.add("Qui est le plus susceptible de changer de bord ?");
        Questions.add("Qui est le plus susceptible de changer de sexe ?");
        Questions.add("Qui est le plus susceptible de se fap devant 2 Girls 1 Cup ?");
        Questions.add("Qui suce le mieux ?");
        Questions.add("Qui est le plus susceptible de s'accoupler avec un alien ?");
        Questions.add("Qui veut le plus se taper l'autre ?");
        Questions.add("Qui est le plus susceptible de mentir à ce jeu ?");
        Questions.add("Qui a le plus regretté un lendemain de soirée arrosée ?");
        Questions.add("Qui a le plus gros appétit ? (Ce coup-ci on parle de sexe !)");
        Questions.add("Qui a le fantasme sexuel le plus hardcore ?");
        Questions.add("Qui a le fétichisme le plus bizarre ?");
        Questions.add("Qui a le plus cherché prolapse dans google dans sa vie ?");
        Questions.add("Qui est le plus facile à mettre dans son lit ?");
        Questions.add("Qui est le plus susceptible de s'être masturbé avec des objets du quotidien ?");
        Questions.add("Qui finit le plus vite (au pieu) ?");
        Questions.add("Qui est le plus bruyant (au pieu) ?");
        Questions.add("Qui a le plus souvent vu ou entendu \"Papa dans Maman\" ?");
        Questions.add("Qui est le plus facile à exciter ?");
        Questions.add("Qui est le plus susceptible de se retrouver à l'hopital avec un objet du quotidien dans le cul ?");
        Questions.add("Qui a probablement le plus de MST ?");
        Questions.add("Qui ferait l'amour sur la musique la plus inapropriée ?");
        Questions.add("Qui serait le plus romantique au lit ?");
        Questions.add("Qui serait le plus susceptible d'être la star d'un porno ?");
        Questions.add("Qui participerait le moins dans une orgie ?");
        Questions.add("Qui serait le plus ouvert à l'échangisme ?");
        Questions.add("Qui est le plus ouvert ? ;) (tu te calmes Julies !!) ");
        Questions.add("Qui pourrait devenir un gigolo/baby sugar ?");

    }
}
